name: "yangyaofei's blog"
description: "记录东西..."
# name:               "yangyaofei's blog"
# description:        "记录东西..."
url: "//blog.yangyaofei.name"
author: "yangyaofei"
# URL
baseurl: ""
permalink: /:year/:month/:day/:title/
# Markdown
markdown: kramdown
# Navigation
# nav:
#   - name:           "About"
#     href:           "//kiko.gfjaru.com/about"
# Sass
sass:
  style:            :compressed
# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
gems:
  - jekyll-seo-tag
