# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name: "yangyaofei's blog"
description: "记录东西..."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url: "//blog.yangyaofei.name"
author: "yangyaofei"

  username:         "yangyaofei"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
# nav:
#   - name:           "About"
#     href:           "//kiko.gfjaru.com/about"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag